### PR TITLE
refactor: remove jquery initial commit

### PR DESCRIPTION
**Pull request by ncrmro**
Just wanted to see your thoughts, I've been dealing with the slow CPA so decided to slim down the javascript payload's.

I have also got working minification and gzip support but will keep this PR simple for initial review.

### CODE REVIEW

**Comment by tonyp7** [comment]
Btw I think the build fails because component.mk needs to be updated too for people using the make build system  instead of cmake.

**Comment by ncrmro** [comment]
> This looks amazing. It probably shows that I am not a front end developer so this help truly is welcome.
> 
> I’ll check on the morrow and merge it!

Hah! but you seem to really know what you are doing with everything else!

**Comment by ncrmro** [comment]
> This looks amazing. It probably shows that I am not a front end developer so this help truly is welcome.
> 
> I’ll check on the morrow and merge it!

@tonyp7  Hah! but you know what you are doing with everything else!

**Comment by tonyp7** [comment]
The other warning with Travis CI is related to a warning with the build script itself being outdated so this is not related to this code that now properly builds.

This is a great update that removes jquery's dependency. I never wanted to have a jquery dependency; nobody wants to pack a 30kb gzipped binary in an embedded project. But I realized my vanilla js skills were simply not there to make it work.

So this is merged with much respects to @ncrmro. Thank you!

**Comment by ncrmro** [comment]
Wewt! thank you and the other contributors !

**Pull request merged**
