### PR TITLE
ESP8266 support and esp-idf component'fy

### PR DESCRIPTION
**Pull request by trombik**
with recent ESP8266 RTOS SDK (v3.2), it is possible to share code on ESP32 and ESP8266. the recent tool-chain builds the original code just fine. to be sure, a `.travis.yml` has been added to the repository. The `.travis.yml` ensures that the code is built on both ESP32 and ESP8266, using legacy `make` method and `idf.py`.

also, the repository is modified so that one can simply import the library as an esp-idf component.

### CODE REVIEW

**Comment by tonyp7** [comment]
That looks awesome! Sorry I didn't have time to check out the complete PR yet -- will do so on the weekend at the latest.

**Comment by trombik** [comment]
@tonyp7 would you enable travis ci in the repository settings? so that (possible) users would be able to see the build status.

**Comment by tonyp7** [comment]
Sure why not! I have never used travis-ci though, and with the dependency to esp-idf it might not be completely trivial to setup. Do you know of any other component I could copy the config from?

**Comment by trombik** [comment]
@tonyp7 the PR you have merged already have `.travis.yml`, which is the configuration file for travis CI. you do not have to do anything other than enable travis ci. just "purchase" the app (it's free for open source projects) at:

https://github.com/marketplace/travis-ci

and enable it in the project.

**Comment by tonyp7** [comment]
Hi @trombik thanks for all the support! I have added the build widget in readme.md.

**Comment by trombik** [comment]
@tonyp7 one of recommended workflow to modify your code is:

* create a branch on your local machine
* push the branch to github
* create a PR
* after making sure that the PR passes tests in travis CI, merge it

this way, no untested code would be merged.

in the github setting, you can completely disable `push to master branch`, including repository owner (i.e. you).

https://help.github.com/en/articles/enabling-branch-restrictions

**Comment by tonyp7** [comment]
I appreciate the efforts you are making to bring this repository into the 21th century!

In reality external contributions and PR are far and few in between so that an "old school" merge can still be done; but regardless I'll have a look at this. It's a nice improvement.

**Pull request merged**
